---
- name: ensure config directory
  file: path="{{ nghttp2_working_dir }}/etc" state=directory

- name: upload config
  template: src="nghttpx.conf" dest="{{ nghttp2_working_dir }}/etc/nghttpx.conf" 
  notify:
     - restart nghttpx

- name: upload priviate key
  copy: "src={{ nghttpx_private_key_file }} dest={{ nghttpx_remote_private_key_file }}"
  notify:
     - restart nghttpx

- name: upload cert
  copy: "src={{ nghttpx_certificate_file }} dest={{ nghttpx_remote_certificate_file }}"
  notify:
     - restart nghttpx

{% if nghttpx_verify_client %}
- name: upload ca cert
  copy: "src={{ nghttpx_verify_client_cacert_file}} dest={{ nghttpx_remote_verify_client_cacert_file }}"
  notify:
     - restart nghttpx
{% endif %}

- name: upload supervisor config
  template: src=supervisor.nghttpx.conf  dest=/etc/supervisor/conf.d/nghttpx.conf 
  notify:
     - restart nghttpx
